fields = ['Direito do Ambiente',
            'Direito Administrativo',
            'Direito Constitucional',
            'Direito da Energia',
            'Direito das Finanças Públicas',
            'Direito Financeiro',
            'Direito Fiscal',
            'Direito Penal',
            'Direito Processual Administrativo',
            'Direito Processual Civil',
            'Direito Processual Penal',
            'Direito Processual do Trabalho',
            'Direito do Urbanismo',
            'Direito dos Contratos',
            'Direito da Família',
            'Direito das Obrigações',
            'Direito Reais',
            'Direito das Sucessões',
            'Direito Comercial',
            'Direito Bancário',
            'Direito Marítimo',
            'Direito das Sociedades Comerciais',
            'Direito dos Valores Mobiliários',
            'Direito dos Transportes',	
            'Direito Aéreo',
            'Direito da Insolvência',
            'Direito Internacional Privado',
            'Direito do Trabalho',
            'Direito da Concorrência',
            'Direito Internacional Público',
            'Direito da UE e Comunitário']


fields_mapping = {'Public':['Direito do Ambiente',
                        'Direito Administrativo',
                        'Direito Constitucional',
                        'Direito da Energia',
                        'Direito das Finanças Públicas',
                        'Direito Financeiro',
                        'Direito Fiscal',
                        'Direito Penal',
                        'Direito Processual Administrativo',
                        'Direito Processual Civil',
                        'Direito Processual Penal',
                        'Direito Processual do Trabalho',
                        'Direito do Urbanismo'],
                    'Private':['Direito dos Contratos',
                            'Direito da Família',
                            'Direito das Obrigações',
                            'Direito Reais',
                            'Direito das Sucessões',
                            'Direito Comercial',
                            'Direito Bancário',
                            'Direito Marítimo',
                            'Direito das Sociedades Comerciais',
                            'Direito dos Valores Mobiliários',
                            'Direito dos Transportes',	
                            'Direito Aéreo',
                            'Direito da Insolvência',
                            'Direito Internacional Privado',
                            'Direito do Trabalho'],
                    'Public-Private':['Direito da Concorrência'],
                    'Public Int.':['Direito Internacional Público'],
                    'UE':['Direito da UE e Comunitário']}


reverse_mapping = {
    field: group 
    for group, fields in fields_mapping.items()
    for field in fields
}